# Generated by Django 4.1.5 on 2023-01-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice', models.CharField(choices=[('ROCK', 'Rock'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('outcome', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('draw', 'Draw')], max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
